name: calendar_io
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  action_slider: ^0.7.0
  animated_bottom_navigation_bar: ^1.3.3
  equatable: ^2.0.7
  flex_color_picker: null
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  get_it: ^8.0.3
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.1
  readmore: ^3.0.0
  skeletonizer: ^1.4.3
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  test:
  mockito:
  get_it:
  get_storage:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
